import tcod

TITLE = 'Untitle Hacking Game'

TILESET = (
    "data/cp437_12x12.png", 16, 16, tcod.tileset.CHARMAP_CP437
)

SCREEN_WIDTH = 120
SCREEN_HEIGHT = 72

CAMERA_WIDTH = 80
CAMERA_HEIGHT = 40

MAP_WIDTH = 160
MAP_HEIGHT = 80

SIDEBAR_WIDTH = SCREEN_WIDTH - CAMERA_WIDTH

SIDEBAR_COMPONENT_HEIGHT = SCREEN_HEIGHT // 4

ACTIONS_HEIGHT = 20
ACTIONS_WIDTH = CAMERA_WIDTH

LOG_HEIGHT = SCREEN_HEIGHT - (ACTIONS_HEIGHT + CAMERA_HEIGHT)
LOG_WIDTH = CAMERA_WIDTH
