import tcod

TITLE = 'Untitle Hacking Game'

TILESET = (
    "data/cp437_12x12.png", 16, 16, tcod.tileset.CHARMAP_CP437
)

SCREEN_WIDTH = 120
SCREEN_HEIGHT = 72

MAP_WIDTH = 80
MAP_HEIGHT = 40

SIDEBAR_WIDTH = SCREEN_WIDTH - MAP_WIDTH

SIDEBAR_COMPONENT_HEIGHT = SCREEN_HEIGHT // 4

ACTIONS_HEIGHT = 20
ACTIONS_WIDTH = MAP_WIDTH

LOG_HEIGHT = SCREEN_HEIGHT - (ACTIONS_HEIGHT + MAP_HEIGHT)
LOG_WIDTH = MAP_WIDTH
